server:
  port: 8084
spring:
  application:
    name: microservice-user
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.artspring.com.cn:3366/yifu_aw?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useServerPrepStmts=false&useAffectedRows=true&autoReconnect=true&cachePrepStmts=true&useSSL=false
    username: yifu_test
    password: ArtYifuTest@2018
    minIdle: 10
    maxActive: 1000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true
    useGlobalDataSourceStat: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zyk.cloud.eurekaclient.model
